spring.application.name=ms-catalogo
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/bd_catalogo
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.hateoas.use-hal-as-default-json=true
