spring.application.name=ms-catalogo
server.port=8082

# Configuración de base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomarket_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

# Para que funcione la HU-6 (HATEOAS)
spring.hateoas.use-hal-as-default-json=true
